services:
  - type: web
    name: vibecompiler-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.src.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: "*"  # You can replace this with your frontend URL in production
      - key: LOG_LEVEL
        value: INFO 