services:
  - type: web
    name: vibe-compiler-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: "https://vibe-compiler.web.app,https://vibe-compiler.firebaseapp.com"
      - key: LOG_LEVEL
        value: INFO 